ch6 finished. CI updated

diff --git a/.github/workflows/kernel-build.yml b/.github/workflows/kernel-build.yml
--- a/.github/workflows/kernel-build.yml
+++ b/.github/workflows/kernel-build.yml
@@ -113,7 +113,7 @@ jobs:
 
       - name: Build kernel and apps
         working-directory: os
-        run: make build ENABLE_FS=0
+        run: make build
 
   qemu:
     runs-on: ubuntu-latest
@@ -160,4 +160,4 @@ jobs:
       - name: Build and run tests in QEMU
         working-directory: os
         run: |
-          timeout 60s make run-test ENABLE_FS=0
+          timeout 120s make run-test || { echo "Test run timed out or failed"; exit 1; }
